### ISSUE TITLE
Reuse of Expert Data Packages in Basic Screening Studies

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#155]
Each DC was requested to create an 'Expert' Data Package for use with Expert Studies in CSIS. While we don't create Expert Studies for each DC, we could still reuse the [respective Data Packages](https://github.com/clarity-h2020/data-package/issues?q=is%3Aissue+is%3Aopen+label%3Adata) in Basic Screening Studies. The following Data Packages are *potentially* available for reuse:

-  [x] [Resccue Data Package](https://github.com/clarity-h2020/data-package/issues/57): Is [available in CSIS](https://csis-dev.myclimateservice.eu/node/2198) and could be used for Basic Screening Studies. Covers only Barcelona. 
- [ ] [DC1 Data Package](https://github.com/clarity-h2020/data-package/issues/20): Draft is [available in CSIS](https://csis-dev.myclimateservice.eu/node/221) but **incomplete**. It contains mainly the EU-level Hazard resources + a few **deprecated** resources which are apparently not available on geoserver.myclimateservice.eu. Data should available on CLARITY sFTP, but integration [is stalled](https://github.com/clarity-h2020/data-package/issues/20#issuecomment-624526468).
- [ ] [DC2 Data Package](https://github.com/clarity-h2020/data-package/issues/21) There are currently two Data Packages in CSIS. More data is available, but integration of additional resources [seems to be stalled](https://github.com/clarity-h2020/data-package/issues/21#issuecomment-587473641). Covers Stockholm only.
  - [x] [Stockholm: Heat related data and indicators](https://csis-dev.myclimateservice.eu/node/221): Contains HC-LE only. <- Note: HC-LE is **not** covered by Basic Screening Studies. If we want to reuse this Data Packages in such studies, we would have to re-tag the resources as HC!
  - [ ] [Stockholm green infrastructure data](https://csis-dev.myclimateservice.eu/node/4008): **incomplete**. It seems to contain EU-level HC layers only.
- [ ] [DC3 Data Package](https://github.com/clarity-h2020/data-package/issues/22): Data Package in CSIS: [DC3 -Urban heat waves, urban heat islands, air ventilation in Linz, Austria, Data Package](https://csis-dev.myclimateservice.eu/node/733). **incomplete** and layers are not working or at least not recognisable since no extent bounding box is defined (Linz assumed). 
- [ ] [DC4 Data Package](https://github.com/clarity-h2020/data-package/issues/23): Data Package in CSIS: [DC4 Spanish Transport Network ](https://csis-dev.myclimateservice.eu/node/705). **incomplete**, there are only 6 layers available.

Note: 'Expert' Data Packages cover only a small area (which *should* be defined in the data package extent bbox). It's unclear how this fact could be respected in Studies, especially if the user has chosen a study area which is outside of spatial coverage of the Data Package.

**Comment by p-a-s-c-a-l** [comment]
It seems that nobody is working any more on the data packages so we can close this issue. 😞
