### ISSUE TITLE
Make new Release DEV -> PROD

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#158]
We've fixed several bugs in DEV instance, changed content and implemented some new features. There are also some security updates to Drupal Core & Modules available, which have to be applied. Now it's time to make a new release.

This is also the prerequisite for making the system accessible by the public. Once this is done, @DenoBeno, @Andrea4ad and others can advertise public CSIS during Webinars, etc.

We have to make sure that the process is **well documented** and can be repeated even when key personnel may not available any more after September 2020.

The required steps are described here:  

- [x] [Importing/Exporting configuration between Dev and Prod environment](https://github.com/clarity-h2020/docker-drupal/issues/138)
- [x] [Importing/Exporting content between Dev & Prod](https://github.com/clarity-h2020/docker-drupal/issues/147)
- [x] Update [Map](https://github.com/clarity-h2020/map-component/issues/101) and [Table](https://github.com/clarity-h2020/simple-table-component/issues/17) Components

--- 
- [x] [Upgrade Drupal Docker Image and Container](https://github.com/clarity-h2020/docker-drupal/issues/156) on DEV
- [x] [Upgrade Drupal Docker Core and Modules](https://github.com/clarity-h2020/docker-drupal/issues/148) on DEV
- [x] [Upgrade Drupal Docker Image and Container](https://github.com/clarity-h2020/docker-drupal/issues/156) on PROD
- [x] [Upgrade Drupal Docker Core and Modules](https://github.com/clarity-h2020/docker-drupal/issues/148) on PROD

Once the updated PROS system is available, we'll start the final round of [internal acceptance tests](https://github.com/clarity-h2020/csis-technical-validation/issues/1) and can invite external users for testing the system.

**Note:** The following features are currently still missing in DEV and are being worked on:
- [Integration of **pluvial flood** model results in CSIS](https://github.com/clarity-h2020/emikat/issues/44)
- [Visualisation of **Adaptation** Scenarios](https://github.com/clarity-h2020/map-component/issues/100)
- [Landing Page for `Testing Team` Users ](https://github.com/clarity-h2020/docker-drupal/issues/157)
- [Reuse of Expert Data Packages in Basic Screening Studies](https://github.com/clarity-h2020/docker-drupal/issues/155)

**Comment by patrickkaleta** [comment]
As discussed during today's telco, I've now synchronized the [configuration](https://github.com/clarity-h2020/docker-drupal/issues/138) and the [content](https://github.com/clarity-h2020/docker-drupal/issues/147). Now waiting for @fgeyer16 to upgrade Drupal on the DEV instance, so that we can fully complete the synchronization.

Sadly, the config_split module is not suitable for handling different user permissions on two Drupal instances. Therefore, during the synchronization the user permissions from DEV were loaded into PROD and I then manually changed it back to how it should be. We will need to find another solution for that (I would suggest handling the user's add/edit rights inside the csis_helpers module).

**Question:**
The csis_helpers module is also up-to-date on PROD but I noticed that the map component could be updated. @therter will you do that? How is it done? For the csis_helpers module it's enough to pull the latest code from the [git repository](https://github.com/clarity-h2020/csis-helpers-module) and clear the cache in Drupal. Does the map component require any additional steps?

**Comment by p-a-s-c-a-l** [comment]
I've updated the description [above](https://github.com/clarity-h2020/docker-drupal/issues/158#issue-651287990) and included a description on how to release new [Map](https://github.com/clarity-h2020/map-component/issues/101) and [Table](https://github.com/clarity-h2020/simple-table-component/issues/17) Components. 

Table and Map are now up-to-date on PROD.

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 I've update docker containers on DEV to the lasted Apache, PHP, Postgres, etc. version. Drupal Core  and Modules have to be [updated separately](https://github.com/clarity-h2020/docker-drupal/issues/148):

```sh
sudo su docker
docker exec -it --user 999 csis-drupal bash
# composer ...
```

CSIS-DEV is now also monitored by UI integrations tests. Please watch [csis-technical-validation](https://github.com/clarity-h2020/csis-technical-validation/) so that you'll get a notification when the [tests fail](https://github.com/clarity-h2020/csis-technical-validation/issues/72). When the tests have passed, we can proceed upgrading PROD.

**Comment by fgeyer16** [comment]
I can not enter docker seems, that I have no permission.

> docker exec -it --user 999 csis-drupal bash
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/csis-drupal/json: dial unix /var/run/docker.sock: connect: permission denied

tried to update locally before tried to update csis-dev so

1. remove '"Issue #2994155": "patches/business_rules_2994155.patch" from composer.patche.json
2. run composer update
3. run vendor/bin/drush updb

should work.

> CSIS-DEV is now also monitored by UI integrations tests

Is there something to do do to trigger that tests or so?

**Comment by p-a-s-c-a-l** [comment]
> I can not enter docker seems, that I have no permission.

I've added you to the docker group. Now it will work. Don't forget to impersonate as docker user otherwise permissions will be messed up.

> should work.

should? 😲 

> Is there something to do do to trigger that tests or so?

Tests are triggered automatically every hour in cismet private ci. If you want to trigger them manually you can commit something (e.g. update readme) to [csis-technical-validation/csis-dev-cypress](https://github.com/clarity-h2020/csis-technical-validation/tree/csis-dev-cypress) branch.

ATM all tests are failing anyway because [EMIKAT seems to have lost the study data](https://github.com/clarity-h2020/emikat/issues/45). 😞

**Comment by p-a-s-c-a-l** [comment]
I've [upgraded ](https://github.com/clarity-h2020/docker-drupal/issues/148#issuecomment-656004316) DEV to Drupal 8.9.2. I'm not going to upgrade PROD until our integration tests are working again.

**Comment by fgeyer16** [comment]
> should? astonished
Having to move a webpage to Europeans commisions servers made very cautious to say will. ;-). Test it thousand times and it works and when it goes live it does not...

**Comment by p-a-s-c-a-l** [comment]
done
